#!/bin/bash
  
EXPECTED_ARGS=1
E_BADARGS=65
MYSQL=`which mysql`
  
Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}"
  
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname"
  exit $E_BADARGS
fi
  
$MYSQL -uroot -p -e "$SQL"

cat ~/site_api/api/sql/create_tables.sql ~/site_api/api/sql/populate_tables.sql > ~/site_api/api/sql/create_sql
$MYSQL -u root -p $1 < ~/site_api/api/sql/create_sql
rm ~/site_api/api/sql/create_sql